version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
