on: push

name: Elixir CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.3
          elixir-version: 1.8
      - run: mix deps.get
      - run: mix test
