name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 21.x
          elixir-version: 1.7.x
      - run: mix deps.get
      - run: mix test
